select NUME,PRENUME,BLOC FROM LOCATARI_TEST where ASOCIATIE="DA";
select NUME,PRENUME,BLOC FROM LOCATARI_TEST where ASOCIATIE="NU";

select NUME,PRENUME, SALARIU,FUNCTIE from ANGAJATI_TEST where FUNCTIE="FONDATOR";
select NUME,PLATA,MAX(INDEX_APA_RECE) from LOCATARI_TEST group by   NUME,PLATA;

select NUME,PLATA,MAX(INDEX_APA_RECE) from LOCATARI_TEST group by NUME,PLATA order by MAX(INDEX_APA_RECE) DESC limit 1;


select NUME,PLATA from LOCATARI_TEST where INDEX_APA_RECE = (select max(INDEX_APA_RECE) from LOCATARI_TEST);

select NUME,PLATA from LOCATARI_TEST where INDEX_APA_RECE = (select max(INDEX_APA_RECE) from LOCATARI_TEST);


select * from LOCATARI_TEST where REST_PLATA=(select max(REST_PLATA) from LOCATARI_TEST);


select c.NUME,c.PRENUME,c.PLATA,c.REST_PLATA,d.NUME_FIRMA,d.DOMENIU,d.DURATA_CONTRACT, c.BLOC
from LOCATARI_TEST c INNER JOIN  CONTRACTE_COLABORARE_TEST d 
on c.BLOC=d.BLOC_ACTIVITATE;

select c.NUME,c.PRENUME,c.PLATA,c.REST_PLATA,c.BLOC from LOCATARI_TEST c where c.BLOC="C4";
-- rosca	sergiu	41.50	11.20	C4

select d.NUME_FIRMA,d.DOMENIU,d.DURATA_CONTRACT,d.BLOC_ACTIVITATE from CONTRACTE_COLABORARE_TEST d where d.BLOC_ACTIVITATE="C4";
-- SC ECO DRILL SRL	CONSTRUCTII	24	C4 

