insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("comorasu","alexandru","ADMINISTRATOR",6, 1700,3);
insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("grigoras","mihai","CASIER",24, 1350,20);
insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("vasiliu","mariana","FEMEIE DE SERVICIU",12, 1500,12);
insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("grigore","andrei","CASIER",6, 1700,15);
insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("mihailescu","alexandru","ELECTRICIAN",12, 2450,10);
insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("rosca","stefan","BOSS",3, 1950,1);
insert into  ANGAJATI_TEST(NUME,PRENUME,FUNCTIE,DURATA_CONTRACT,SALARIU,CONCEDIU) values ("tenea","alexandru","CONTABIL",36, 1650,16);

select * from ANGAJATI_TEST;
