insert into LOCATARI_TEST(ASOCIATIE,NUME, PRENUME,BLOC, NR_PERSOANE_INTRETINERE,INDEX_APA_RECE,PLATA) values ("DA","stamate","mihai","C2",3,5, 335.8);
insert into LOCATARI_TEST(ASOCIATIE,NUME, PRENUME,BLOC, NR_PERSOANE_INTRETINERE,INDEX_APA_RECE,PLATA) values ("NU","rosca","sergiu","C4",1,7,41.5);
insert into LOCATARI_TEST(ASOCIATIE,NUME, PRENUME,BLOC, NR_PERSOANE_INTRETINERE,INDEX_APA_RECE,PLATA) values ("DA","mihailescu","monica","C2",2,22,441.5);
insert into LOCATARI_TEST(ASOCIATIE,NUME, PRENUME,BLOC, NR_PERSOANE_INTRETINERE,INDEX_APA_RECE,PLATA) values ("DA","mihailescu","monica","C2",2,22,441.5);

select * from LOCATARI_TEST;
