insert into CONTRACTE_COLABORARE_TEST(NUME_FIRMA,BLOC_ACTIVITATE,DOMENIU,CUI,DURATA_CONTRACT,VALOARE_SERVICII,REST_PLATA) values ("SC BLABLA SRL","C2","CONSTRUCTII",4754986, 12,3500, 180);
insert into CONTRACTE_COLABORARE_TEST(NUME_FIRMA,BLOC_ACTIVITATE,DOMENIU,CUI,DURATA_CONTRACT,VALOARE_SERVICII,REST_PLATA) values ("SC RAZVAN SA","C3","SERVICII", 5865946, 6,850, 1700);
insert into CONTRACTE_COLABORARE_TEST(NUME_FIRMA,BLOC_ACTIVITATE,DOMENIU,CUI,DURATA_CONTRACT,VALOARE_SERVICII,REST_PLATA) values ("SC ADERACOM SRL","C2","TRANSPORT",2352893, 36,8500, 3700);
insert into CONTRACTE_COLABORARE_TEST(NUME_FIRMA,BLOC_ACTIVITATE,DOMENIU,CUI,DURATA_CONTRACT,VALOARE_SERVICII,REST_PLATA) values ("SC SINPUR ENERGY SRL","C2","TELECOMUNICATII",4754986, 12,2750, 800);
insert into CONTRACTE_COLABORARE_TEST(NUME_FIRMA,BLOC_ACTIVITATE,DOMENIU,CUI,DURATA_CONTRACT,VALOARE_SERVICII,REST_PLATA) values ("SC ECO DRILL SRL","C4","CONSTRUCTII",8759685, 24,5500, 200);

select * from CONTRACTE_COLABORARE_TEST;
